// app/layout.tsx
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "@/components/custom/Header/Header";
import Footer from "@/components/custom/Footer/Footer";
import CartIcon from "@/components/custom/CartIcon/CartIcon";
import { apiClient } from "@/lib/apiClient";
import axios from "axios";
import { cookies } from "next/headers";
import { Car } from "lucide-react";
import { CartProvider } from "@/components/providers/CartProvider";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
  display: "swap", // Optional but recommended for performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionId = (await cookies()).get("session_id")?.value || "";
  return (
    <html lang="en" className={urbanist.variable}>
      <body className="antialiased">
        <CartProvider sessionId={sessionId} />
        <Header />
        {children}
        <Footer />
        <CartIcon />
      </body>
    </html>
  );
}
